### PR TITLE
Improve license information

### PR DESCRIPTION
**Pull request by tarsius**
* Rename COPYING to LICENSE, which is more common nowadays and is
  more explicit about what text to expect in there.
* Remove some text previously added to the front of the license text.
  That helps tools that try to automatically detect what license is
  being used.
* Add the standard permission statement to the library header.

### CODE REVIEW

**Comment by BartMassey** [comment]
Thanks much for your suggestions per my license information. Is `emacs-page` being considered for inclusion within `emacs` proper? If so, you should be aware that it has some notable bugs.

**Comment by tarsius** [comment]
No it is not. But Richard considers all Elisp to be derived from Emacs. Following that logic it has to be released under a license that is compatible to the one used by Emacs. Which is why, as the maintainer of the [Emacsmirror](https://emacsmirror.net), I have to be able to tell (preferably in an automated fashion) what a package's license is.

**Comment by BartMassey** [comment]
I'm afraid I'm not willing to remove my copyright notice from my COPYING file, nor alter the header text on my elisp source file to the much more verbose suggested form. I chose the name COPYING for the license file because it was the name chosen by Richard for this purpose. So I'm afraid I'm going to leave things as I found them.

By the way, the assertion that writing in a particular programming language gives any rights to the work to the programming language creator is both legally and ethically highly questionable. In a quick Google search I can't find any assertion by RMS to the effect that elisp programs are derived from emacs. Can you point me to a specific statement of his that makes this claim?

Sorry to be a pain. Thanks for your interest in my software.

**Comment by tarsius** [comment]
Would you be willing to add the line

```
;; License: GPL-3+
```

to the header instead?

Some longer variants exist, but I am guessing you prefer the short one :wink: 

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
```

> By the way, the assertion that writing in a particular programming language gives any rights to the work to the programming language creator is both legally and ethically highly questionable. In a quick Google search I can't find any assertion by RMS to the effect that elisp programs are derived from emacs. Can you point me to a specific statement of his that makes this claim?

I am afraid I cannot find anything right now either. Actually he does not claim that all Elisp has to be releases under a compatible license, just all code that uses APIs provided by Emacs that cannot be found in other lisps. I.e. if you can port your extension to Common Lisp with only minor modifications, then it does not derive from Emacs.

**Comment by BartMassey** [comment]
OK, I've added your license tag to my elisp. Hopefully this will be adequate for you. I've closed the pull request.

> Actually he does not claim that all Elisp has to be releases under a compatible license, just all code that uses APIs provided by Emacs that cannot be found in other lisps. I.e. if you can port your extension to Common Lisp with only minor modifications, then it does not derive from Emacs.

I'd really like to see a specific public statement from RMS to this effect. It's not something I can recall him saying previously.

**Pull request closed without merging**
